### ISSUE TITLE
Security issue: a default tls private key is given in plain text in the source code

### ISSUE THREAD

**Issue by fresheneesz** [andris9/smtp-server#34]
This is a significant security issue. Obviously anyone serious about security should be using their own private keys. But this library shouldn't be making it easy for people to build insecure mail servers. A private key isn't private if its in a public repository like this. If the user doesn't give their own TLS keys, the server simply shouldn't accept TLS. 

Doing it this way also makes it pretty confusing if you want to set up a mail server entirely without TLS.

**Comment by andris9** [comment]
I don't agree that this is a security issue. Pregenerated keys are a feature not a bug as the main goal for this project is to provide easy to setup test or lightweight SMTP servers. If you want to have a full featured production server, use [Haraka](https://haraka.github.io/).

**Comment by fresheneesz** [comment]
@andris9 If the goal is to make TLS support easy, why not use your own `pem` module to generate TLS keys so no private key is exposed publicly, even in "easy" cases? Wouldn't that solve the problem without sacrificing an easy test setup?

**Comment by andris9** [comment]
I wanted to use *pem* at first but it does not work well with Windows as it expects openssl to be installed. *Ursa* would have been a better choice as it has direct bindings to openssl instead of running command line stuff like *pem* but I do not like to include dependencies that require compilation in my public modules.

**Comment by fresheneesz** [comment]
"I do not like to include dependencies that require compilation in my public modules"

Why not?

**Comment by andris9** [comment]
I had problems with these in the past. Nodemailer had `iconv` as a dependency and it caused a lot of complaints. Compiling is slow (total pain when developing locally and need to often reinstall dependencies), it doesn't work everywhere (eg. in Windows without Visual Studio, also a lot of production servers do not include a compiler for security reasons, some environments require special settings for the compile to succeed etc.), upgrading Node.js usually means recompilation. Anyway it turned out that including compiled stuff should be knowingly made decision (maybe for speed, maybe there are no alternatives) and not something sneaked in by a dependency of a dependency.
